name: personal_packages
version: 0.0.1
homepage: https://github.com/AvoMandjian/personal_packages
description: A new Flutter package project.
environment: 
  sdk: '>=2.14.4 <3.0.0'
  flutter: '>=1.17.0'

dependencies: 
  cached_network_image: any
  extended_image: any
  flutter_facebook_auth: any
  flutter_screenutil: any
  get: any
  get_storage: any
  google_sign_in: any
  http: any
  intl_phone_number_input: any
  line_icons: any
  onesignal_flutter: any
  auto_size_text: any
  carousel_slider: any
  smooth_page_indicator: any
  flutter_svg: ^1.0.0
  flutter_email_sender: 5.0.2
  zoom_pinch_overlay: 1.1.2
  shadowed_image: 1.0.3
  pinch_zoom: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: null
