# fastlane add_plugin flutter_version_manager

  lane :git do
    flutter_version_manager(
      arguments: "-patch",
      yml: "/Users/avomandjian/Documents/FlutterConfig/packages/personal_packages/version.yml",
      pubspec: "/Users/avomandjian/Documents/FlutterConfig/packages/personal_packages/pubspec.yaml",
      # git_repo: "https://github.com/AvoMandjian/personal_packages.git"
      )
    git_commit(path: '*',message: "ref")
    push_to_git_remote(
        remote: "https://github.com/AvoMandjian/personal_packages.git",         # optional, default: "origin"
        # local_branch: "develop",  # optional, aliased by "branch", default is set to current branch
        # remote_branch: "develop", # optional, default is set to local_branch
        # force: true,    # optional, default: false
        # force_with_lease: true,   # optional, default: false
        # tags: false,    # optional, default: true
        # no_verify: true,# optional, default: false
        # set_upstream: true        # optional, default: false
      )
    # add actions here: https://docs.fastlane.tools/actions
end
